import 'package:tim_ui_kit_sticker_plugin/utils/tim_custom_face_data.dart';

class ConstData {
  static final List<CustomEmojiFaceData> emojiList = [
    CustomEmojiFaceData(
        name: '4349',
        icon: "naughty.png",
        isEmoji: true,
        list: [
          "loveYou.png",
          "love.png",
          "loveHeart.png",
          "arrogant.png",
          "superciliousLook.png",
          "lollipop.png",
          "embrace.png",
          "claspFist.png",
          "blastedRebar.png",
          "despise.png",
          "shutUp.png",
          "firecrackers.png",
          "shit.png",
          "wipeSweat.png",
          "ribbon.png",
          "coloredBall.png",
          "kitchenKnife.png",
          "bad.png",
          "bankNote.png",
          "carriage.png",
          "yawn.png",
          "soldier.png",
          "cry.png",
          "cake.png",
          "knife.png",
          "proud.png",
          "lightBulb.png",
          "fade.png",
          "naughty.png",
          "cloudy.png",
          "daze.png",
          "tremble.png",
          "aircraft.png",
          "blowKiss.png",
          "struggle.png",
          "windmill.png",
          "awkward.png",
          "seduce.png",
          "applause.png",
          "shy.png",
          "sillySmile.png",
          "lantern.png",
          "Xi.png",
          "snicker.png",
          "wave.png",
          "lookBack.png",
          "hunger.png",
          "excitement.png",
          "streetDance.png",
          "terrified.png",
          "surprised.png",
          "coffee.png",
          "kowtow.png",
          "lovely.png",
          "pitiful.png",
          "pickNose.png",
          "skeleton.png",
          "cool.png",
          "willCry.png",
          "sleepy.png",
          "candle.png",
          "basketball.png",
          "coldSweat.png",
          "giftBag.png",
          "gift.png",
          "sweat.png",
          "tear.png",
          "mahjong.png",
          "microphone.png",
          "cat.png",
          "kissYou.png",
          "rose.png",
          "rice.png",
          "noodle.png",
          "feedingBottle.png",
          "sad.png",
          "alarmClock.png",
          "anger.png",
          "sulk.png",
          "football.png",
          "beer.png",
          "ladybug.png",
          "curlLip.png",
          "tableTennis.png",
          "car.png",
          "great.png",
          "knock.png",
          "frog.png",
          "embarrassed.png",
          "fist.png",
          "weak.png",
          "flirting.png",
          "sofa.png",
          "delete.png",
          "lightning.png",
          "victory.png",
          "showLove.png",
          "pistol.png",
          "decline.png",
          "sleep.png",
          "sun.png",
          "ropeSkipping.png",
          "jump.png",
          "titter.png",
          "spit.png",
          "grievance.png",
          "handshake.png",
          "watermelon.png",
          "rain.png",
          "scare.png",
          "offerKiss.png",
          "banana.png",
          "chineseChess.png",
          "heartbreak.png",
          "envelope.png",
          "panda.png",
          "shh.png",
          "drug.png",
          "doubt.png",
          "insidious.png",
          "rightLocomotive.png",
          "rightHum.png",
          "rightTaiChi.png",
          "umbrella.png",
          "moon.png",
          "halo.png",
          "bye.png",
          "bomb.png",
          "torment.png",
          "tissue.png",
          "swearing.png",
          "pig.png",
          "crazy.png",
          "circle.png",
          "baredTeeth.png",
          "diamondRing.png",
          "leftLocomotive.png",
          "leftHum.png",
          "leftTaiChi.png",
          "NO.png",
          "OK.png",
        ])
  ];
  static final emojiMapList = {
    'loveYou': '爱你',
    'love': "爱情",
    'loveHeart': "爱心",
    'arrogant': '傲慢',
    'superciliousLook': '白眼',
    "lollipop": '棒棒糖',
    "embrace": '抱抱',
    "claspFist": '抱拳',
    "blastedRebar": '爆筋',
    "despise": '鄙视',
    "shutUp": '闭嘴',
    "firecrackers": '鞭炮',
    "shit": '便便',
    "wipeSweat": '擦汗',
    "ribbon": '彩带',
    "coloredBall": '彩球',
    "kitchenKnife": '菜刀',
    "bad": '差劲',
    "bankNote": "钞票",
    "carriage": '车厢',
    "yawn": '打哈欠',
    "soldier": '大兵',
    "cry": "大哭",
    "cake": '蛋糕',
    "knife": "刀",
    "proud": '得意',
    "lightBulb": '灯泡',
    "fade": '凋谢',
    "naughty": '调皮',
    "cloudy": '多云',
    "daze": '发呆',
    "remble": '发抖t',
    "aircraft": '飞机',
    "blowKiss": '飞吻',
    "struggle": '奋斗',
    "windmill": '风车',
    "awkward": '尴尬',
    "seduce": '勾引',
    "applause": '鼓掌',
    "shy": '害羞',
    "sillySmile": '憨笑',
    "lantern": '红灯笼',
    "Xi": '红双喜',
    "snicker": '坏笑',
    "wave": '挥手',
    "lookBack": '回头',
    "hunger": '饥饿',
    "excitement": '激动',
    "streetDance": '街舞',
    "terrified": '惊恐',
    "surprised": '惊讶',
    "coffee": '咖啡',
    "kowtow": '磕头',
    "lovely": '可爱',
    "pitiful": '可怜',
    "pickNose": '抠鼻',
    "skeleton": '骷髅',
    "cool": '酷',
    "willCry": '快哭了',
    "sleepy": '困',
    "candle": '蜡烛',
    "basketball": '篮球',
    "coldSweat": '冷汗',
    "giftBag": '礼品袋',
    "gift": '礼物',
    "sweat": '流汗',
    "tear": '流泪',
    "mahjong": '麻将',
    "microphone": '麦克风',
    "cat": '猫咪',
    "kissYou": '么么哒',
    "rose": '玫瑰',
    "rice": '米饭',
    "noodle": '面条',
    "feedingBottle": '奶瓶',
    "sad": '难过',
    "alarmClock": '闹钟',
    "anger": '怒',
    "sulk": '怄火',
    "football": '皮球',
    "beer": '啤酒',
    "ladybug": '瓢虫',
    "curlLip": '撇嘴',
    "tableTennis": '乒乓',
    "car": '汽车',
    "great": '强',
    "knock": '敲打',
    "frog": '青蛙',
    "embarrassed": '糗大了',
    "fist": '拳头',
    "weak": '弱',
    "flirting": '色',
    "sofa": '沙发',
    "delete": '删除',
    "lightning": '闪电',
    "victory": '胜利',
    "showLove": '示爱',
    "pistol": '手枪',
    "decline": '衰',
    "sleep": '睡觉',
    "sun": '太阳',
    "ropeSkipping": '跳绳',
    "jump": '跳跳',
    "titter": '偷笑',
    "spit": '吐',
    "grievance": '委屈',
    "handshake": "握手",
    "watermelon": '西瓜',
    "rain": '下雨',
    "scare": '吓',
    "offerKiss": '献吻',
    "banana": '香蕉',
    "chineseChess": '象棋',
    "heartbreak": '心碎了',
    "envelope": '信封',
    "panda": '熊猫',
    "shh": '嘘',
    "drug": '药',
    "doubt": '疑问',
    "insidious": '阴险',
    "rightLocomotive": '右车头',
    "rightHum": '右哼哼',
    "rightTaiChi": "右太极",
    "umbrella": '雨伞',
    "moon": '月亮',
    "halo": '晕',
    "bye": '再见',
    "bomb": '炸弹',
    "torment": '折磨',
    "tissue": '纸巾',
    "swearing": '咒骂',
    "pig": '猪头',
    "crazy": '抓狂',
    "circle": '转圈',
    "baredTeeth": '龇牙',
    "diamondRing": "钻戒",
    "leftLocomotive": '左车头',
    "leftHum": '左哼哼',
    "leftTaiChi": "左太极",
    "NO": "NO",
    "OK": 'OK',
  };
}
